name: BetterPvP
version: '1.0.5-Stable'
main: io.github.sstudiosdev.BetterPvP
api-version: '1.13'
author: Sstudiosdev, staFF6773, Akit, pichema, 1vcbGH and more
website: https://sstudiosdev.is-a.dev/donate
depend: [Vault]
softdepend: [PlaceholderAPI, WorldGuard]