name: Tag Release

on:
  push:
    tags:
      - '*'

jobs:
  send-discord-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Send Discord Embed Webhook
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_TAG: ${{ github.ref }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        sudo apt-get install -y jq
        TAG_NAME=$(echo $GITHUB_TAG | sed 's/refs\/tags\///')
        TAG_URL="https://github.com/$GITHUB_REPOSITORY/releases/tag/$TAG_NAME"
        DESCRIPTION=$(git tag -l --format='%(contents)' $TAG_NAME)
        PAYLOAD=$(jq -n --arg title "$TAG_NAME" --arg description "$DESCRIPTION" --arg url "$TAG_URL" '{
          "embeds": [
            {
              "title": $title,
              "description": $description,
              "url": $url,
              "color": 3447003
            }
          ]
        }')
        curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" $DISCORD_WEBHOOK_URL

    - name: Send Discord @everyone Message
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        PAYLOAD=$(jq -n --arg content "@everyone New tag created!" '{
          "content": $content
        }')
        curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" $DISCORD_WEBHOOK_URL
